name: Release & Docker

on:
  push:
    # on branche like main or 2.6, 2.64, 10.12
    branches: ['main', '[0-9]+.[0-9]+']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: '.'
          push: true
          tags: |
            laurentc35/my-pogues:latest,
            laurentc35/my-pogues:${{steps.version.outputs.prop}}
  docker-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'next/package.json'
          prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: './next'
          push: true
          tags: |
            laurentc35/my-pogues:test-pogues
